### ISSUE TITLE
Haven Pool 

### ISSUE THREAD

**Issue by swanseahost** [dvandal/cryptonote-nodejs-pool#126] opened 2018-05-15 23:22 UTC
Hi All,

Sorry to raise another post here.

I can't get the haven pool working.  Here -> http://haven.ucrypto.com shows NA on all except the network hash.

The admin shows the daemon and wallet is working fine and node is running but NA.

Where did I go wrong ?

Thanks

**Comment by dvandal** [comment] 2018-05-16 01:32
Hi, please update your website files under pages/ folder which have changed today.

**Comment by swanseahost** [comment] 2018-05-16 07:41
You sir are a legend!

Could you tell me why the charts are not showing underneath too ?

Thank you again!
Steve

**Comment by dvandal** [comment] 2018-05-16 13:43
I don't reproduce, charts enabled in config.json ?

**Comment by dvandal** [comment] 2018-05-16 14:36
The issue is that API is not bound to 0.0.0.0 and so charts data collector is unable to access to API data, working on a fix.

**Comment by dvandal** [comment] 2018-05-16 15:12
All issues fixed now.

**Closed** 2018-05-16 15:13 UTC

**Comment by bradstines** [comment] 2018-05-23 16:34
I get this error when loading pool.....

root@xhv:~/pool# node init.js
Failed to read config file config.json

SyntaxError: Unexpected token } in JSON at position 1618
/root/pool/lib/logger.js:29
var logDir = config.logging.files.directory;
             ^

ReferenceError: config is not defined
    at Object.<anonymous> (/root/pool/lib/logger.js:29:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/pool/init.js:17:1)
    at Module._compile (module.js:652:30)
