### ISSUE TITLE
Pool server ports don't open if monerd isn't running

### ISSUE THREAD

**Issue by cbarraford** [dvandal/cryptonote-nodejs-pool#4] opened 2018-03-01 15:16 UTC
If you start monerod, then start init.js, everything works great.

But if you start init.js then start monerod, the pool server ports (ie 3333 5555 8888 etc) never recover and never open. 

So it seems theres a race condition between monerod and init.js starting

**Comment by dvandal** [comment] 2018-03-08 21:20
Thanks for reporting this issue. The issue is fixed now and the code has been patched.

**Closed by dvandal** 2018-03-08 21:20 UTC
Labels: bug
